# 新版 docker-compose 不需要指定版本
# version: '3.9'

services:
  fif-mysql:
    image: 'mysql:5.7'
    container_name: 'fif-mysql'
    restart: unless-stopped
    command:
      # 设置字符集
      - '--character-set-server=utf8'
      - '--collation-server=utf8_general_ci'
    volumes:
      - 'fif-mysql-d:/var/lib/mysql'
      # 用于初始化数据库
      # 需要修改
      # - '../sql:/docker-entrypoint-initdb.d/'
    environment:
      - MYSQL_ROOT_PASSWORD=mysql123@fif
      - TZ=Asia/Shanghai
    networks:
      - fif-net
    ports:
      - '3306:3306'
    tty: true
    stdin_open: true

# networks:
#   mysql-s:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 10.9.8.0/24
#           gateway: 10.9.8.1

volumes:
  mysql-d:
  
