#!/bin/bash

# 下载文件
# curl https://github.com/zen-browser/desktop/releases/download/1.0.1-a.19/zen-specific.AppImage



# https://github.com/zen-browser/desktop/releases/download/twilight/zen-specific.AppImage