#!/bin/bash

# 转换
# ll-appimage-convert convert --url "https://github.com/zen-browser/desktop/releases/download/twilight/zen-specific.AppImage" --name "twilight-zen-browser" --id "twilight.zen-browser.app" --version "1.0.1-t.19" --description "The browser made for you, not your data."

ll-appimage-convert convert -f ./zen-specific.AppImage --name "twilight-zen-browser" --id "twilight.zen-browser.app" --version "1.0.1.19" --description "The browser made for you, not your data." -b